name: Main Deployment Pipeline

on:
  push:
    branches:
      - dev

permissions:
  id-token: write
  contents: read

jobs:
  call-terraform-workflow:
    uses: ./.github/workflows/terraform.yaml
    secrets: inherit

  call-app-deploy-workflow:
    needs: call-terraform-workflow
    uses: ./.github/workflows/app_deploy.yaml
    secrets: inherit